---
booktitle: Proceedings of the 2nd Conference on Topology, Algebra, and Geometry in
  Data Science(TAG-DS 2026)
shortname: TAG-DS
title: Proceedings of Machine Learning Research
shorttitle: TAG-DS 2026
volume: '334'
year: '2026'
start: &1 2026-08-18
end: 2026-08-20
published: 2026-08-16
url: https://proceedings.mlr.press
number: '2'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: tagds2026
month: 0
tex_title: Topology, Algebra, and Geometry in Data Science(TAG-DS 2026)
cycles: false
bibtex_editor: Berman, Eddie and Bern{\'a}rdez, Guillermo and Chen, Samantha and Cloninger,
  Alex and Doster, Timothy and Emerson, Tegan and Grigsby, J. Elisenda and Kvinge,
  Henry and Lawrence, Hannah and Marrinan, Tim and Myers, Audun and Papillon, Mathilde
  and Tahmasebi, Behrooz and Telyatnikov, Lev and Walters, Robin and Weber, Melanie
  and Xie, YuQing and Yeats, Eric
editor:
- given: Eddie
  family: Berman
- given: Guillermo
  family: Bernárdez
- given: Samantha
  family: Chen
- given: Alex
  family: Cloninger
- given: Timothy
  family: Doster
- given: Tegan
  family: Emerson
- given: J. Elisenda
  family: Grigsby
- given: Henry
  family: Kvinge
- given: Hannah
  family: Lawrence
- given: Tim
  family: Marrinan
- given: Audun
  family: Myers
- given: Mathilde
  family: Papillon
- given: Behrooz
  family: Tahmasebi
- given: Lev
  family: Telyatnikov
- given: Robin
  family: Walters
- given: Melanie
  family: Weber
- given: YuQing
  family: Xie
- given: Eric
  family: Yeats
description: |
  Proceedings of the 2nd Conference on Topology, Algebra, and Geometry in Data Science(TAG-DS 2026)
    Held in Boston, Massachusetts, USA on 18-20 August 2026

  Published as Volume 334 by the Proceedings of Machine Learning Research on 16 August 2026.

  Volume Edited by:
    Eddie Berman
    Guillermo Bernárdez
    Samantha Chen
    Alex Cloninger
    Timothy Doster
    Tegan Emerson
    J. Elisenda Grigsby
    Henry Kvinge
    Hannah Lawrence
    Tim Marrinan
    Audun Myers
    Mathilde Papillon
    Behrooz Tahmasebi
    Lev Telyatnikov
    Robin Walters
    Melanie Weber
    YuQing Xie
    Eric Yeats

  Series Editors:
    Neil D. Lawrence
    Hoel Kervadec
    Tegan Emerson
date_str: 18--20 Aug
author:
  name: PMLR
baseurl: "/v334"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v334
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v334
email: ''
conference:
  name: Topology, Algebra, and Geometry in Data Science (TAG-DS 2026)
  url:
  location: Boston, Massachusetts, USA
  dates:
  - *1
  - 2026-08-19
  - 2026-08-20
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: TAGDS2026_clean.bib
# Site settings
# Original source:  TAGDS2026_clean.bib
